// <auto-generated />
namespace Rvas_ispit_projekat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class populatePublishers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populatePublishers));
        
        string IMigrationMetadata.Id
        {
            get { return "202106121728028_populatePublishers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
